apiVersion: v1
kind: ConfigMap
metadata:
  name: rag-config
  namespace: ai-platform
data:
  EMBEDDING_URL: "http://embedding-service.ai-platform:8080"
  QDRANT_URL: "http://qdrant.ai-data:6333"
  QDRANT_COLLECTION: "raj-docs"
  OLLAMA_URL: "http://host.k3d.internal:11434"
  OLLAMA_MODEL: "llama3.2:latest"
  REDIS_URL: "redis://redis.ai-data:6379"
  TOP_K: "3"
  KAFKA_BOOTSTRAP: "kafka.ai-data:9092"
  LANGFUSE_PUBLIC_KEY: "pk-lf-ca45825c-e015-4c7c-b8bc-ed14572ec860"
  LANGFUSE_SECRET_KEY: "sk-lf-053f2654-f967-4c5d-9612-0405a54c41af"
  LANGFUSE_HOST: "http://langfuse.ai-platform:3001"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-service
  namespace: ai-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-service
  template:
    metadata:
      labels:
        app: rag-service
    spec:
      containers:
        - name: rag
          image: raj/rag-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: rag-config
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: rag-service
  namespace: ai-platform
spec:
  selector:
    app: rag-service
  ports:
    - name: http
      port: 8000
