apiVersion: apps/v1
kind: Deployment
metadata:
  name: normalizer
  namespace: ai-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: normalizer
  template:
    metadata:
      labels:
        app: normalizer
    spec:
      containers:
        - name: normalizer
          image: raj/normalizer:latest
          imagePullPolicy: Never
          env:
            - name: KAFKA_BOOTSTRAP
              value: "kafka-kafka-bootstrap.ai-data:9093"
            - name: KAFKA_SECURITY_PROTOCOL
              value: "SSL"
            - name: KAFKA_CERT_DIR
              value: "/etc/kafka-certs"
          volumeMounts:
            - name: kafka-certs
              mountPath: /etc/kafka-certs
              readOnly: true
          readinessProbe:
            exec:
              command: ["python3", "-c", "import os; os.getpid()"]
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["python3", "-c", "import os; os.getpid()"]
            initialDelaySeconds: 20
            periodSeconds: 15
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
      volumes:
        - name: kafka-certs
          secret:
            secretName: normalizer
