apiVersion: apps/v1
kind: Deployment
metadata:
  name: normalizer
  namespace: ai-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: normalizer
  template:
    metadata:
      labels:
        app: normalizer
    spec:
      containers:
        - name: normalizer
          image: raj/normalizer:latest
          imagePullPolicy: Never
          env:
            - name: KAFKA_BOOTSTRAP
              value: "kafka.ai-data:9092"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
