FROM python:3.12-slim
RUN pip install --no-cache-dir fastapi uvicorn sentence-transformers
COPY model/ /app/model/
COPY 05-embedding-code.py /app/main.py
ENV TRANSFORMERS_OFFLINE=1
ENV HF_HUB_OFFLINE=1
CMD ["python", "/app/main.py"]
